import java.awt.GridBagLayout
import java.awt.GridBagConstraints
import javax.swing.border.EmptyBorder

apply plugin: 'com.android.application'

System.setProperty('java.awt.headless','false')

//Uncomment to debug deprecation warnings.
/* tasks.withType(JavaCompile) {
	options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
} */

android {
	namespace "::APP_PACKAGE::"
	compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
	buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION
	::if (ANDROID_GRADLE_PLUGIN>="4.0")::ndkPath '::ANDROID_NDK_ROOT_ESCAPED::'::end::
	::if (ANDROID_NDK_VERSION)::ndkVersion '::ANDROID_NDK_VERSION::'::end::

	defaultConfig {
		applicationId "::META_PACKAGE_NAME::"
		minSdkVersion Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
		targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)
		versionCode Integer.parseInt(project.VERSION_CODE)
		versionName project.VERSION_NAME
		::if (languages != null)::resConfigs ::foreach languages::"::__current__::", ::end::""::end::
	}

	::if KEY_STORE::
	signingConfigs {
		if (project.KEY_STORE_PASSWORD == 'null') {
			def keyStoreFile = project.KEY_STORE.split('/')
			keyStoreFile = keyStoreFile[keyStoreFile.length - 1]
			project.KEY_STORE_PASSWORD = getPassword('\nPlease enter key password for ' + keyStoreFile + ':');
		}

		if (project.KEY_STORE_ALIAS_PASSWORD == 'null') {
			project.KEY_STORE_ALIAS_PASSWORD = getPassword("\nPlease enter key alias password for alias " + project.KEY_STORE_ALIAS + ":")
		}

		release {
			storeFile file(project.KEY_STORE)
			storePassword project.KEY_STORE_PASSWORD
			keyAlias project.KEY_STORE_ALIAS
			keyPassword project.KEY_STORE_ALIAS_PASSWORD
		}
	}
	::else::
	File signingFile = file('signing.properties')
	if(signingFile.exists()) {
		Properties signing = new Properties()
		signing.load(new FileInputStream(signingFile))

		signingConfigs {
			release {
				storeFile file(signing["KEY_STORE"])
				storePassword signing["KEY_STORE_PASSWORD"]
				keyAlias signing["KEY_STORE_ALIAS"]
				keyPassword signing["KEY_STORE_ALIAS_PASSWORD"]
			}
		}
	} else {
		signingConfigs {
			release
		}
	}
	::end::

	buildTypes {
		release {
			minifyEnabled false
			signingConfig signingConfigs.release
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
		}
	}

	::if (ANDROID_PLAY_ASSETS_DELIVERY_PACKS)::
	assetPacks = [::foreach (ANDROID_PLAY_ASSETS_DELIVERY_PACKS):: ":::__current__::" ::end::]
	::end::
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	::if (ANDROID_LIBRARY_PROJECTS)::::foreach (ANDROID_LIBRARY_PROJECTS)::implementation project(':deps:::name::')
	::end::::end::
	::if (ANDROID_LIBRARY_DEPENDENCIES)::::foreach (ANDROID_LIBRARY_DEPENDENCIES)::implementation('::__current__::')
	::end::::end::
}

tasks.whenTaskAdded { task ->
	if (task.name.startsWith("bundle") && task.name != "bundle") {
		task.doLast {
			def flavor = task.name.substring("bundle".length()).uncapitalize()
			def outputDir = "${buildDir}/outputs/bundle/${flavor}"
			def originalFile = file("${outputDir}/app-${flavor}.aab")
			def renamedFile = file("${outputDir}/::APP_FILE::-${flavor}.aab")

			if (renamedFile.exists()) {
				renamedFile.delete()
			}

			if (originalFile.exists()) {
				originalFile.renameTo(renamedFile)
			}
		}
	} else if (task.name.startsWith("assemble") && task.name != "assemble") {
		task.doLast {
			def flavor = task.name.substring("assemble".length()).uncapitalize()
			def outputDir = "${buildDir}/outputs/apk/${flavor}"
			def originalFile = file("${outputDir}/app-${flavor}.apk")
			def renamedFile = file("${outputDir}/::APP_FILE::-${flavor}.apk")

			if (renamedFile.exists()) {
				renamedFile.delete()
			}

			if (originalFile.exists()) {
				originalFile.renameTo(renamedFile)
			}
		}
	}
}

def getPassword(String message) {
    if (project.hasProperty("RELEASE_STORE_PASSWORD")) {
        return project.property("RELEASE_STORE_PASSWORD")
    }

    def console = System.console()
    if (console != null) {
        return new String(console.readPassword("\n" + message + ": "))
    }

    try {
        println("\n" + message + " (enter password in terminal): ")
        def reader = new BufferedReader(new InputStreamReader(System.in))
        return reader.readLine()
    } catch (Exception e) {
        throw new GradleException("Failed to access terminal input. Please provide the password via project properties.")
    }
}
